import ButtonRed from './button-red.js';
import ButtonPink from './button-pink.js';
import ButtonPurple from './button-purple.js';
import ButtonDeepPurple from './button-deep-purple.js';
import ButtonIndigo from './button-indigo.js';
import ButtonBlue from './button-blue.js';
import ButtonLightBlue from './button-light-blue.js';
import ButtonCyan from './button-cyan.js';
import ButtonTeal from './button-teal.js';
import ButtonGreen from './button-green.js';
import ButtonLightGreen from './button-light-green.js';
import ButtonLime from './button-lime.js';
import ButtonYellow from './button-yellow.js';
import ButtonAmber from './button-amber.js';
import ButtonOrange from './button-orange.js';
import ButtonDeepOrange from './button-deep-orange.js';
import ButtonBrown from './button-brown.js';
import ButtonGrey from './button-grey.js';
import ButtonBlueGrey from './button-blue-grey.js';
import ButtonBlack from './button-black.js';

customElements.define('button-red', ButtonRed);
customElements.define('button-pink', ButtonPink);
customElements.define('button-purple', ButtonPurple);
customElements.define('button-deep-purple', ButtonDeepPurple);
customElements.define('button-indigo', ButtonIndigo);
customElements.define('button-blue', ButtonBlue);
customElements.define('button-light-blue', ButtonLightBlue);
customElements.define('button-cyan', ButtonCyan);
customElements.define('button-teal', ButtonTeal);
customElements.define('button-green', ButtonGreen);
customElements.define('button-light-green', ButtonLightGreen);
customElements.define('button-lime', ButtonLime);
customElements.define('button-yellow', ButtonYellow);
customElements.define('button-amber', ButtonAmber);
customElements.define('button-orange', ButtonOrange);
customElements.define('button-deep-orange', ButtonDeepOrange);
customElements.define('button-brown', ButtonBrown);
customElements.define('button-grey', ButtonGrey);
customElements.define('button-blue-grey', ButtonBlueGrey);
customElements.define('button-black', ButtonBlack);
